# Generated by Django 5.2.3 on 2025-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tournaments",
            "0003_alter_tournament_end_date_alter_tournament_game_day_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_league",
            field=models.BooleanField(default=False),
        ),
    ]
