"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.4.
Docs:
- https://docs.djangoproject.com/en/5.2/topics/settings/
- https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import pathlib

import dj_database_url

# ─────────────────────
# 📁 Core Paths
# ─────────────────────
BASE_DIR = pathlib.Path(__file__).resolve().parent.parent

# ─────────────────────
# 🔐 Security Settings
# ─────────────────────
SECRET_KEY = "django-insecure-w7o_woit6@neqmfx-k3jy(jl$3@qfd33v^exh^2bc6+m$12nn("
DEBUG = os.environ.get("DEBUG", "False") == "True"
ALLOWED_HOSTS = ["*"]  # 🔒 Update this in production!

# ─────────────────────
# 👥 Authentication
# ─────────────────────
AUTH_USER_MODEL = "users.CustomUser"
LOGIN_URL = "/login"

# ─────────────────────
# 🧩 Installed Apps
# ─────────────────────
INSTALLED_APPS = [
    # Third-party
    "rest_framework",
    "rest_framework.authtoken",
    "djoser",
    "corsheaders",
    # Local apps
    "tournaments",
    "users",
    # Django built-ins
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# ─────────────────────
# ⚙️ Middleware
# ─────────────────────
MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ─────────────────────
# 🌐 URL Routing
# ─────────────────────
ROOT_URLCONF = "config.urls"

# ─────────────────────
# 🧱 Templates
# ─────────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ─────────────────────
# 🚀 WSGI
# ─────────────────────
WSGI_APPLICATION = "config.wsgi.application"

# ─────────────────────
# 🗄️ Database
# ─────────────────────
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# ─────────────────────
# 🔐 Password Validators
# ─────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ─────────────────────
# 🌍 Internationalization
# ─────────────────────
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ─────────────────────
# 🖼️ Static Files
# ─────────────────────
STATIC_URL = "/static/"
STATIC_ROOT = str(BASE_DIR / "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ─────────────────────
# 🔢 Primary Key Type
# ─────────────────────
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ─────────────────────
# 🔌 Django REST Framework
# ─────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# ─────────────────────
# 🌐 CORS Configuration
# ─────────────────────
CORS_ALLOWED_ORIGINS = [
    "https://pickleball-o6zu.onrender.com",
]
