name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: pickleball-backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pylint coverage

      - name: Run Pylint
        working-directory: pickleball-backend
        run: |
          source venv/bin/activate
          pylint tournaments --load-plugins pylint_django > pylint-report.txt || true

      - name: Run tests with coverage
        working-directory: pickleball-backend
        run: |
          source venv/bin/activate
          coverage run manage.py test
          coverage report
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-pickleball
